#!/usr/bin/env bash

# Define the IP addresses
localhost_ip="127.0.0.2"
facebook_ip="8.8.8.8"

# Modify the /etc/hosts file
cp /etc/hosts new_hosts

sed -i "s/127.0.0.1.*/$localhost_ip localhost/" new_hosts
echo "$facebook_ip facebook.com" >> new_hosts

cp new_hosts /etc/hosts
